### ISSUE TITLE
System.UriFormatException in 0.13.1

### ISSUE THREAD

**Issue by pekspro** [DaveTCode/FreshdeskApiDotnet#165]
Version `0.12.1` works fine for me. But when I upgrade to 0.13.1 I get an `System.UriFormatException` for everything I do it feels like:

    Invalid URI: The format of the URI could not be determined.

Sample code:

``` C#
FreshdeskClient freshdeskClient = FreshdeskClient.Create(/* ulr */, /* api-key */);

// This throws
await foreach (var a in client.Solutions.ListAllCategoriesAsync())
{
    return true;
}

// And this throws
await foreach (var a in client.Tickets.ListAllTicketsAsync(new FreshdeskApi.Client.Tickets.Requests.ListAllTicketsRequest()))
{
    return true;
}

// And this throws
await foreach (var a in client.Agents.ListAllAgentsAsync(new FreshdeskApi.Client.Agents.Requests.ListAllAgentsRequest()))
{
    return true;
}
```

This happens both in .NET 6 and .NET 7.

**Comment by trejjam** [comment]
Thans for reporting. I did not expect this:
![obrazek](https://user-images.githubusercontent.com/3594540/207826256-661aedf9-3b27-4684-aa1d-7bb27d6492c3.png)
It requires uri to be Absolute, not RelativeOrAbsolute.

**Comment by trejjam** [comment]
Can you test with your subscription (I am no longer Freshdesk customer) this branch:
https://github.com/trejjam/FreshdeskApiDotnet/tree/fix/issues-165

Please test at least 3 contacts, so pagination kicks in.

**Comment by InfobricPek** [comment]
Just some quick feedback. In the demo project in Program.cs on line 47:

    new PagingConfiguration(0, 2)

This causes an exception. Freshdesk doesn't allow 0 to be page number. Changing 0 to 1 works:

    new PagingConfiguration(1, 2)


In FreshdeskApi.Client.GetPagedResults you changed this:

    new Uri(url, UriKind.Relative)

Which is fine for the first request. But it is an absolute request for the next page. This works:

    new Uri(url, UriKind.RelativeOrAbsolute)

Will test more a bit later.

**Comment by pekspro** [comment]
I have tested more and with the changes above everything seems to work :-)

I'm a bit concerned that you no longer have access to Freshdesk :-( It there something I can help with?

**Comment by trejjam** [comment]
Thank you for your feedback. I tried to obtain a testing account for this library, but they didn't even reply. I will try again

In the worst case, there are 30 days testing accounts

**Comment by trejjam** [comment]
There should be 0.13.2 soon available
