### ISSUE TITLE
Recent changes to URI parsing have broken my app's api call

### ISSUE THREAD

**Issue by keziashirazi98** [DaveTCode/FreshdeskApiDotnet#168]
Hi,

I noticed you made some recent changes to the URI parsing. Upgrading the package in my app from 0.12.0 to 0.13.1 broke the API call to Freshdesk it is making. The code it was running is:

`await _freshdeskClient
                .SearchSolutionsAsync(searchText, paging)
                .Where(s => s.FolderVisibility == FolderVisibility.AllUsers ||
                            s.FolderVisibility == FolderVisibility.LoggedInUsers ||
                            s.FolderVisibility == FolderVisibility.SelectedContactSegments ||
                            s.FolderVisibility == FolderVisibility.SelectedCompanySegments)
                .Take(11)
                .ToListAsync();`

The error thrown was "Invalid URI: The format of the URI could not be determined".

When reverting back to using the 0.12.0 tag of this package this error stopped being thrown.

Thanks,
Kezia

**Comment by trejjam** [comment]
Hi the 0.13.2 has fixed the issue, at least I think so: https://github.com/DaveTCode/FreshdeskApiDotnet/issues/165

**Comment by trejjam** [comment]
Closed for inactivity
