### ISSUE TITLE
FEAT: Add ability to configure through json

### ISSUE THREAD

**Issue by HavenDV** [DaveTCode/FreshdeskApiDotnet#215]
I think it's simple, just need to add code like this:
<img width="745" alt="image" src="https://github.com/DaveTCode/FreshdeskApiDotnet/assets/3002068/a34d3a5b-c823-4439-9b2d-2db9f8dd54b7">

**Comment by trejjam** [comment]
Hi, if I am not wrong this should be possible due to:
![image](https://github.com/DaveTCode/FreshdeskApiDotnet/assets/3594540/70ed0fad-6ead-470c-9e62-9cd876574ac8)

You can do setup this way:
```cs
services.AddOptions<IocExtensions.FreshdeskConfiguration>() //Maybe nested class is not marvelous syntax for this, but it works
  .BindConfiguration(...);

services.AddFreshdeskApiClient(configureHttpClientBuilder: httpClientBuilder => {});
```
instead of:
```cs
services.AddFreshdeskApiClient(
  options: freshdeskConfiguration => {
    freshdeskConfiguration.FreshdeskDomain = "";
    freshdeskConfiguration.ApiKey = "";
  },
  configureHttpClientBuilder: httpClientBuilder => {}
);
```

**Comment by HavenDV** [comment]
Thanks for the quick response. Yes, this is possible in the way you indicated. It was a suggestion to add this by default to AddFreshdeskApiClient.

**Comment by trejjam** [comment]
Ah. We can add another extension method:

```cs
public static IServiceCollection AddFreshdeskApiClient(
    this IServiceCollection serviceCollection,
    Action<OptionsBuilder<FreshdeskConfiguration>> optionsBuilder,
    Action<IHttpClientBuilder>? configureHttpClientBuilder = null
)
```

But I am not sure there is a big gain. I like the standard way of managing it on my own using `services.AddOptions`.

Or is it about being coupled? (`AddFreshdeskApiClient + OptionsBuilder<FreshdeskConfiguration>`)

**Comment by HavenDV** [comment]
I suggest replacing
```cs
serviceCollection.AddOptions();
```
with
```
_ = serviceCollection
    .AddOptions<FreshdeskConfiguration>()
    .BindConfiguration(configSectionPath: "Freshdesk");
```

I didn't suggest PR because I'm not 100% sure what AddOptions does now, I haven't used this approach before

**Comment by trejjam** [comment]
It's a different thing. It only ensure, that options infrastructure is registered:

```cs
/// <summary>
/// Adds services required for using options.
/// </summary>
/// <param name="services">The <see cref="IServiceCollection"/> to add the services to.</param>
/// <returns>The <see cref="IServiceCollection"/> so that additional calls can be chained.</returns>
public static IServiceCollection AddOptions(this IServiceCollection services)
{
    ThrowHelper.ThrowIfNull(services);

    services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptions<>), typeof(UnnamedOptionsManager<>)));
    services.TryAdd(ServiceDescriptor.Scoped(typeof(IOptionsSnapshot<>), typeof(OptionsManager<>)));
    services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptionsMonitor<>), typeof(OptionsMonitor<>)));
    services.TryAdd(ServiceDescriptor.Transient(typeof(IOptionsFactory<>), typeof(OptionsFactory<>)));
    services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptionsMonitorCache<>), typeof(OptionsCache<>)));
    return services;
}
```

**Comment by HavenDV** [comment]
Got it, not sure if this is necessary then.
Then I suggest just adding the code above instead of replacing

**Comment by trejjam** [comment]
I do not really like "magic" config discovery using hard-coded string names. I added the possibility of configuring it with an overload of `AddFreshdeskApiClient` see #217 .

When done inside the library you "steal" the possibility to configure the builder the way you might need. i.e.
![image](https://github.com/DaveTCode/FreshdeskApiDotnet/assets/3594540/775524c3-ed92-449a-a778-870835618dc1)
