### ISSUE TITLE
Doesn't look like this library supports ticket attachments?

### ISSUE THREAD

**Issue by derekantrican** [DaveTCode/FreshdeskApiDotnet#33]
Title says it all - support for ticket attachments?

If not, I have a gist for creating a FreshDesk ticket with attachments here: https://gist.github.com/derekantrican/1ac9702c7b13317226ec0c3212906a6a based on their sample here: https://github.com/freshworks/fresh-samples/blob/master/C-Sharp/CreateTicketWithAttachment.cs

**Comment by DaveTCode** [comment]
Yes, unfortunately the instance which I built this library to support makes use of a 3rd party (SendSafely) for attachments so we never had use of a direct attachment API.

If I was to build a branch with this function would you have any way to test it out?

**Comment by derekantrican** [comment]
If you mean "test it out" as in, "I have a freshdesk domain & a way to test out some C# code" then yes - I could test it out

**Comment by DaveTCode** [comment]
Turns out someone had the same idea - #35 is going through review now. Feel free to comment on it if it doesn't look like it would cover your use case

**Comment by DaveTCode** [comment]
Never came back to this ticket but presumably you got notified that the MR was merged and released. I'll close this now anyway
