### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by trejjam** [DaveTCode/FreshdeskApiDotnet#56]
Hi,

what do you think about Github Actions support? Instead of Github Pipelines.

**Comment by DaveTCode** [comment]
Works for me! All my professional experience is with Gitlab CI so I've only got superficial knowledge of github actions vs ADO pipelines, if memory serves they use the same fundamental backend so it should be straightforward enough to migrate. 

It'd be a useful thing for me to learn properly so I might take a look at some point in the next week, no objection if you wanted to just submit another MR for it though.

**Comment by DaveTCode** [comment]
Alright, lets say this is done now. The Myget feed works, the nuget feed push probably works (we'll find out when I release your attachement changes) and the pushes work (including sonarcloud checks)
