### ISSUE TITLE
FreshDesk InvalidFreshdeskRequest Exception when subject not provided

### ISSUE THREAD

**Issue by shubhambothara** [DaveTCode/FreshdeskApiDotnet#60]
When using the NuGet, Bad Request Exception is returned from Freshdesk when subject is not included in the CreateTicket function call. But the API documentation says you can pass in null.

**Comment by DaveTCode** [comment]
Hi, 

To be clear, are you proposing that this library should make "Subject" mandatory in the constructor for CreateTicketRequest?

https://github.com/DaveTCode/FreshdeskApiDotnet/blob/master/FreshdeskApi.Client/Tickets/Requests/CreateTicketRequest.cs#L14

How confident are you that all requests to Freshdesk with subject null are rejected with 400s? Their API documentation is notoriously wrong but I'm wondering what level of testing you've done?

Dave
