### ISSUE TITLE
Unable to add attachments with the latest available nuget(0.8.0)

### ISSUE THREAD

**Issue by shubhambothara** [DaveTCode/FreshdeskApiDotnet#65]
While navigating through the code on Github I see an IEnumerable for attachments for Conversations and Tickets but I don't see it in the nuget. Can we have an update to the nuget with these fields?

**Comment by shubhambothara** [comment]
![image](https://user-images.githubusercontent.com/33233934/115128595-8503be00-9fa4-11eb-9964-a493934b7494.png)

**Comment by DaveTCode** [comment]
Could you try the newly published 0.8.1 package? I've just released it from master on GitHub so it should be fine!

**Comment by shubhambothara** [comment]
Thanks Dave, that worked. Also, is there a plan to support attachments for ConversationEntry? I see it's supported in Freshdesk documentation. I believe it will be similar to tickets.

**Comment by trejjam** [comment]
@shubhambothara 
I think, it is already supported. See https://github.com/DaveTCode/FreshdeskApiDotnet/blob/858198ae7279b044c3645692bdbaa45fc32e9a22/FreshdeskApi.Client/Conversations/Requests/CreateReplyRequest.cs#L50

**Comment by shubhambothara** [comment]
@trejjam 
Yes, they are there when you create a reply to a ticket but they don't get returned when we get the ticket conversations

**Comment by trejjam** [comment]
@shubhambothara Please, take a look at #66 and test it maybe?
